//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMR.FA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allocation
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int PropertyId { get; set; }
        public Nullable<decimal> Allocation1 { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Property Property { get; set; }
    }
}
