//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMR.FA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyFinance
    {
        public int Id { get; set; }
        public int PropertyId { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public Nullable<decimal> Expense { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
